### ISSUE TITLE
[BUG] An item with the same key has already been added

### ISSUE THREAD

**Issue by warlordattack** [androidseb25/iGotify-Notification-Assistent#112]
Hello, i migrated docker container from one server to an other, and it starts, but then it stops with an error.
Please help :) ... perhaps an IF NOT EXIST is missing somewhere

```
Gotify - Url: https://...
Is Gotify - Url available: yes
SecNtfy Server - Url: https://api.secntfy.app
Is SecNtfy Server - Url available: yes
Client - Token: CetzbBOv.Mx8U9o
Client connecting...
Done!
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: CetzbBOv.Mx8U9o
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartWsConn(String gotifyServerUrl, String clientToken) in /src/Services/GotifySocketService.cs:line 74
   at iGotify_Notification_Assist.Services.GotifySocketService.<>c__DisplayClass9_0.<StartWsThread>b__0() in /src/Services/GotifySocketService.cs:line 47
```

**Comment by androidseb25** [comment]
Did you copy the database from the data folder, too?

When yes normally it's checking if it exists.

I take a deeper look after my holiday vacation.

**Comment by androidseb25** [comment]
In the current dev build you will find a fix.

When you will try it you can pull it here...

`docker pull ghcr.io/androidseb25/igotify-notification-assist-dev:latest`

**Comment by androidseb25** [comment]
Comes ahead with the 1.4.2 release of the iOS App
