### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by andre1808** [androidseb25/iGotify-Notification-Assistent#50]
**Describe the bug**
Regelmäßige disconnects und daher kein Push mehr auf iOS. 
Im Container log steht dann das folgende:
`2024-04-12T15:49:21.437447000Z Done!
2024-04-12T15:49:21.445113000Z Disconnection happened, type: Websocket.Client.DisconnectionInfo
2024-04-13T06:53:26.310039000Z warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
2024-04-13T06:53:26.310352000Z       Failed to determine the https port for redirect.
`
Lässt sich nur durch restart des Containers beheben. 

**Expected behavior**
Keine Disconnects :)

**Smartphone (please complete the following information):**
 - Device: iPhone 15 Pro
 - OS: iOS 17.4
 - Version of Container 1.2.0.2
 - Version of iGotify 1.2.1
 - Server version 2.4.0 (20)

**Comment by androidseb25** [comment]
Was steht den oberhalb des Logs kann er den prüfen ob er verbunden ist?

Normalerweise verbindet er sich automatisch sobald er nen disconnect bekommt...

Kann es auch sein das dein gotify Container ab und zu keine Verbindung zulässt?

**Comment by andre1808** [comment]
Hier mal das ganze log.
Eigentlich sollte er nichts blocken. Hab das docker compose file aus der Doku genommen. 

`2024-04-12T14:56:44.631569000Z Unhandled exception. System.Net.Http.HttpRequestException: Name or service not known (gotify.blackert.eu:443)
2024-04-12T14:56:44.631698000Z  ---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name or service not known
2024-04-12T14:56:44.631747000Z    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
2024-04-12T14:56:44.631785000Z    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
2024-04-12T14:56:44.631821000Z    at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
2024-04-12T14:56:44.631859000Z    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
2024-04-12T14:56:44.631892000Z    --- End of inner exception stack trace ---
2024-04-12T14:56:44.631922000Z    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
2024-04-12T14:56:44.631953000Z    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2024-04-12T14:56:44.631984000Z    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2024-04-12T14:56:44.632016000Z    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
2024-04-12T14:56:44.632048000Z    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
2024-04-12T14:56:44.632078000Z    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
2024-04-12T14:56:44.632109000Z    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2024-04-12T14:56:44.632137000Z    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
2024-04-12T14:56:44.632164000Z    at SecNtfyNuGet.SecNtfy.CheckIfUrlReachable(String url)
2024-04-12T14:56:44.632193000Z    at iGotify_Notification_Assist.Services.GotifySocketService.Start() in /src/Services/GotifySocketService.cs:line 101
2024-04-12T14:56:44.632221000Z    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
2024-04-12T14:56:44.632248000Z    at System.Threading.ThreadPoolWorkQueue.Dispatch()
2024-04-12T14:56:44.632277000Z    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
2024-04-12T14:56:45.547910000Z Database is created: True
2024-04-12T14:56:53.727400000Z Unhandled exception. System.Net.Http.HttpRequestException: Name or service not known (gotify.blackert.eu:443)
2024-04-12T14:56:53.727546000Z  ---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name or service not known
2024-04-12T14:56:53.727595000Z    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
2024-04-12T14:56:53.727631000Z    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
2024-04-12T14:56:53.727666000Z    at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
2024-04-12T14:56:53.727701000Z    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
2024-04-12T14:56:53.727733000Z    --- End of inner exception stack trace ---
2024-04-12T14:56:53.727763000Z    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
2024-04-12T14:56:53.727794000Z    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2024-04-12T14:56:53.727825000Z    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2024-04-12T14:56:53.727858000Z    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
2024-04-12T14:56:53.727888000Z    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
2024-04-12T14:56:53.727916000Z    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
2024-04-12T14:56:53.727946000Z    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2024-04-12T14:56:53.727974000Z    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
2024-04-12T14:56:53.728002000Z    at SecNtfyNuGet.SecNtfy.CheckIfUrlReachable(String url)
2024-04-12T14:56:53.728033000Z    at iGotify_Notification_Assist.Services.GotifySocketService.Start() in /src/Services/GotifySocketService.cs:line 101
2024-04-12T14:56:53.728064000Z    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
2024-04-12T14:56:53.728100000Z    at System.Threading.ThreadPoolWorkQueue.Dispatch()
2024-04-12T14:56:53.728133000Z    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
2024-04-12T14:56:54.597493000Z Database is created: True
2024-04-12T14:56:55.236801000Z Gotify - Url: https://gotify.blackert.eu
2024-04-12T14:56:55.236929000Z Is Gotify - Url available: yes
2024-04-12T14:56:55.236973000Z SecNtfy Server - Url: https://api.secntfy.app
2024-04-12T14:56:55.237007000Z Is SecNtfy Server - Url available: yes
2024-04-12T14:56:55.237120000Z Client - Token: CvGefF6TVajoIbK
2024-04-12T14:56:55.241354000Z Client connecting...
2024-04-12T14:56:55.281891000Z Done!
2024-04-12T14:56:55.294038000Z info: Microsoft.Hosting.Lifetime[14]
2024-04-12T14:56:55.294170000Z       Now listening on: http://[::]:8080
2024-04-12T14:56:55.295947000Z info: Microsoft.Hosting.Lifetime[0]
2024-04-12T14:56:55.296027000Z       Application started. Press Ctrl+C to shut down.
2024-04-12T14:56:55.296571000Z info: Microsoft.Hosting.Lifetime[0]
2024-04-12T14:56:55.296641000Z       Hosting environment: Production
2024-04-12T14:56:55.296785000Z info: Microsoft.Hosting.Lifetime[0]
2024-04-12T14:56:55.296840000Z       Content root path: /app
2024-04-12T15:04:13.543283000Z Message converted: {"id":185,"appid":4,"message":"```\n\nDetails\n=======\nVMID    Name      Status    Time    Size           Filename                                                               \n213     gotify    ok        28s     852.693 MiB    /mnt/ext_ssd_backup/dump/vzdump-lxc-213-2024_04_12-17_03_45.tar.zst    \n\n\nTotal running time: 28s\n\nLogs\n====\nvzdump 213 --all 0 --node homeserver --compress zstd --notification-mode auto --mode snapshot --mailnotification always --storage ext_ssd_backup --notes-template '{{guestname}}'\n\n\n213: 2024-04-12 17:03:45 INFO: Starting Backup of VM 213 (lxc)\n213: 2024-04-12 17:03:45 INFO: status = running\n213: 2024-04-12 17:03:45 INFO: CT Name: gotify\n213: 2024-04-12 17:03:45 INFO: including mount point rootfs ('/') in backup\n213: 2024-04-12 17:03:45 INFO: backup mode: snapshot\n213: 2024-04-12 17:03:45 INFO: ionice priority: 7\n213: 2024-04-12 17:03:45 INFO: create storage snapshot 'vzdump'\n213: 2024-04-12 17:03:46 INFO: creating vzdump archive '/mnt/ext_ssd_backup/dump/vzdump-lxc-213-2024_04_12-17_03_45.tar.zst'\n213: 2024-04-12 17:04:12 INFO: Total bytes written: 2325422080 (2.2GiB, 84MiB/s)\n213: 2024-04-12 17:04:12 INFO: archive file size: 852MB\n213: 2024-04-12 17:04:12 INFO: adding notes to backup\n213: 2024-04-12 17:04:13 INFO: cleanup temporary 'vzdump' snapshot\n213: 2024-04-12 17:04:13 INFO: Finished Backup of VM 213 (00:00:28)\n\n\n\n```","title":"vzdump backup status (homeserver.local): backup successful","priority":1,"extras":{"clientdisplay":{"contentType":"text/markdown"}},"date":"2024-04-12T17:04:13.503233978+02:00"}
2024-04-12T15:04:13.543471000Z 
2024-04-12T15:04:13.608684000Z WS Instance from: CvGefF6TVajoIbK
2024-04-12T15:04:13.946876000Z MvPaHZ4rSzlzzcdB3EqYoIzuVOEdrkJuqu+msMnjmkqsps7seFsTucq57+ju5VFfQfotlCYmCuf3oqEkf40ZDWJk26SApt+XKV+6QgczY1muMlWJEyAvrVQsD66bsMbKK+owmz4CrOu4uASE+xrqAq4z4qs4cbUogWLOC26Pu3djRsErUNbgP/z6v8y89Uhj0sPw8mIfaMQF3MTJpK/6VWpf3wP/RNjuzLGzpZk6ZhKfm/mbovaU8sSn3EAQuPAxyK75JRH6fef02Mtsa7G8ZVxrrBAeawv9xQwpwJ3atxKnLgQRZOcF87ndBsaEoi9VHZrzzLgbxt+7tsyJRFoa2A==
2024-04-12T15:13:49.922866000Z Message converted: {"id":186,"appid":4,"message":"```\n\nDetails\n=======\nVMID    Name             Status    Time        Size    Filename    \n100     homeassistant    err       1min 10s    0 B     null        \n200     VM 200           todo      \u003c0.1s       0 B     null        \n201     VM 201           todo      \u003c0.1s       0 B     null        \n210     VM 210           todo      \u003c0.1s       0 B     null        \n211     VM 211           todo      \u003c0.1s       0 B     null        \n251     VM 251           todo      \u003c0.1s       0 B     null        \n252     VM 252           todo      \u003c0.1s       0 B     null        \n254     VM 254           todo      \u003c0.1s       0 B     null        \n\n\nTotal running time: 1min 10s\n\nLogs\n====\nvzdump --mailto andre.blackert@gmail.com --all 1 --node homeserver --storage ext_ssd_backup --notification-mode notification-system --exclude 212,213 --prune-backups 'keep-last=4' --notes-template '{{guestname}}' --mailnotification always --mode stop --compress zstd\n\n\n100: 2024-04-12 17:12:39 INFO: Starting Backup of VM 100 (qemu)\n100: 2024-04-12 17:12:39 INFO: status = running\n100: 2024-04-12 17:12:39 INFO: backup mode: stop\n100: 2024-04-12 17:12:39 INFO: ionice priority: 7\n100: 2024-04-12 17:12:39 INFO: VM Name: homeassistant\n100: 2024-04-12 17:12:39 INFO: include disk 'scsi0' 'local-lvm:vm-100-disk-1' 32G\n100: 2024-04-12 17:12:39 INFO: include disk 'efidisk0' 'local-lvm:vm-100-disk-0' 4M\n100: 2024-04-12 17:12:39 INFO: stopping virtual guest\n100: 2024-04-12 17:12:56 INFO: creating vzdump archive '/mnt/ext_ssd_backup/dump/vzdump-qemu-100-2024_04_12-17_12_39.vma.zst'\n100: 2024-04-12 17:12:56 INFO: starting kvm to execute backup task\n100: 2024-04-12 17:12:57 INFO: started backup task 'c03d0575-22b1-4c05-98d1-d6f1f0b1e0ce'\n100: 2024-04-12 17:12:57 INFO: resuming VM again after 18 seconds\n100: 2024-04-12 17:13:00 INFO:   2% (837.0 MiB of 32.0 GiB) in 3s, read: 279.0 MiB/s, write: 203.3 MiB/s\n100: 2024-04-12 17:13:03 INFO:   4% (1.5 GiB of 32.0 GiB) in 6s, read: 220.0 MiB/s, write: 194.8 MiB/s\n100: 2024-04-12 17:13:06 INFO:   6% (2.0 GiB of 32.0 GiB) in 9s, read: 171.6 MiB/s, write: 152.1 MiB/s\n100: 2024-04-12 17:13:09 INFO:  11% (3.6 GiB of 32.0 GiB) in 12s, read: 570.3 MiB/s, write: 121.9 MiB/s\n100: 2024-04-12 17:13:12 INFO:  12% (4.1 GiB of 32.0 GiB) in 15s, read: 164.3 MiB/s, write: 155.4 MiB/s\n100: 2024-04-12 17:13:15 INFO:  15% (4.8 GiB of 32.0 GiB) in 18s, read: 241.7 MiB/s, write: 186.5 MiB/s\n100: 2024-04-12 17:13:18 INFO:  17% (5.5 GiB of 32.0 GiB) in 21s, read: 233.2 MiB/s, write: 162.9 MiB/s\n100: 2024-04-12 17:13:21 INFO:  19% (6.1 GiB of 32.0 GiB) in 24s, read: 217.5 MiB/s, write: 189.5 MiB/s\n100: 2024-04-12 17:13:24 INFO:  21% (6.8 GiB of 32.0 GiB) in 27s, read: 221.1 MiB/s, write: 203.7 MiB/s\n100: 2024-04-12 17:13:27 INFO:  23% (7.5 GiB of 32.0 GiB) in 30s, read: 241.7 MiB/s, write: 192.7 MiB/s\n100: 2024-04-12 17:13:30 INFO:  26% (8.6 GiB of 32.0 GiB) in 33s, read: 368.5 MiB/s, write: 152.6 MiB/s\n100: 2024-04-12 17:13:34 INFO:  32% (10.5 GiB of 32.0 GiB) in 37s, read: 480.3 MiB/s, write: 130.7 MiB/s\n100: 2024-04-12 17:13:37 INFO:  35% (11.5 GiB of 32.0 GiB) in 40s, read: 357.1 MiB/s, write: 260.6 MiB/s\n100: 2024-04-12 17:13:40 INFO:  42% (13.6 GiB of 32.0 GiB) in 43s, read: 701.1 MiB/s, write: 204.8 MiB/s\n100: 2024-04-12 17:13:43 INFO:  44% (14.3 GiB of 32.0 GiB) in 46s, read: 268.5 MiB/s, write: 256.2 MiB/s\n100: 2024-04-12 17:13:46 INFO:  49% (15.9 GiB of 32.0 GiB) in 49s, read: 546.2 MiB/s, write: 224.1 MiB/s\n100: 2024-04-12 17:13:48 ERROR: interrupted by signal\n100: 2024-04-12 17:13:48 INFO: aborting backup job\n100: 2024-04-12 17:13:48 INFO: resuming VM again\n100: 2024-04-12 17:13:49 ERROR: Backup of VM 100 failed - interrupted by signal\n\n200: no log available\n\n201: no log available\n\n210: no log available\n\n211: no log available\n\n251: no log available\n\n252: no log available\n\n254: no log available\n\n\n\n```","title":"vzdump backup status (homeserver.local): backup failed: interrupted by signal","priority":9,"extras":{"clientdisplay":{"contentType":"text/markdown"}},"date":"2024-04-12T17:13:49.906578403+02:00"}
2024-04-12T15:13:49.923123000Z 
2024-04-12T15:13:49.923253000Z WS Instance from: CvGefF6TVajoIbK
2024-04-12T15:13:50.197193000Z tALzso8iyDfrJFLJCKnKsfVUlCaAo/vd6j7vWnXnPKogxdPUq7xdqrkbEtsBPc8tTgWyTGY5qJLRvI75Ulrt/uYsaZBy8yjeNC1Vy0JXXkXEZsm3t3ff+d/Mg8rCepMMO9MfMwiJhCJAvCc2LlKUvXNdCX207tnkklUEaoG1vCV4RpwYLQA++1ZGWzesjzDC8xcYHTpOELaLA6idXv4DAPpoVpmQBc+rRxY1erTy9eBg6Knj6t+P77rpk/jyoEDB/EgLihsHaOIApTvN62JUW8XOw5xVOyExX/dsbPAcP6cFYiekJKG0fukNZc8noQ+ncYLFxVGe/pv1+9XN6o1CpA==
2024-04-12T15:17:23.268931000Z Message converted: {"id":187,"appid":5,"message":"Watchtower 1.7.1\nUsing notifications: gotify\nChecking all containers (except explicitly disabled with label)\nScheduling first run: 2024-04-13 00:00:00 +0200 CEST\nNote that the first check will be performed in 6 hours, 42 minutes, 36 seconds\n","title":"Watchtower updates on bc361982c94f","priority":0,"date":"2024-04-12T17:17:23.246384886+02:00"}
2024-04-12T15:17:23.269112000Z 
2024-04-12T15:17:23.269185000Z WS Instance from: CvGefF6TVajoIbK
2024-04-12T15:17:23.395397000Z SKfw/5ij6BREkqY8fw8eD1C/zsmwqA1IuoNgdnyhB1cEDbLPYrCBwDRr5xGJahsyQMHuJdbxidXZ08YNZUTgCBW3uYct7SYsIrg1k1El6S1eZHyqXtklfnn1Q+p4DWD5se028q3ndcsi7M71bptxQygHxzhP7ejxXPPFHS0JM5W65wwzVZvIljHfNy5w8eh+puhQq5cbzaWPNiXred3guIRp/ih+4qWKXAG4V8iFMu0bpchpGtiT4GuSVwlDgjRY7tpR0t9jhAWdP55qz0PVZ9np9yGME3RfLkQHGdZjNfPedeZI/uJkvOy6EIzNrpbr4KvpaEgDXQTSqs3q7kwtNg==
2024-04-12T15:48:32.953500000Z Message converted: {"id":188,"appid":7,"message":"Watchtower 1.7.1\nUsing notifications: gotify\nChecking all containers (except explicitly disabled with label)\nScheduling first run: 2024-04-13 00:00:00 +0200 CEST\nNote that the first check will be performed in 6 hours, 11 minutes, 27 seconds\n","title":"Watchtower updates on bbc560a5ed65","priority":0,"date":"2024-04-12T17:48:32.934859168+02:00"}
2024-04-12T15:48:32.953619000Z 
2024-04-12T15:48:32.953768000Z WS Instance from: CvGefF6TVajoIbK
2024-04-12T15:48:33.382123000Z owjv1wKm3VUOGIRheIsgTEOZu5rE7ZT9yR3AZ7VWtEdK29eitQxBwCpwO31vTTZCL5w0ePlKFIcZyBxol6D9dBjpNGg1kdC1bu3fs4eDIeS6zVbFa0mdkizMUNYsToETiZ6OL2ng1ALd1BuJqRsuAdxHtuR4wTBXxqDq23XzUideVDEQd/rtKaOw26ZEKIvKz5Zzc2CCGJw8JlT2rlKm+RIzYwVF5Wv/xo6dGBrKg5jN832fOzIVIc9YC1QW/zMeMauB8zDFG7cK+rqaTSyEpVkk03N2aeUmr9C9GyE7KmTivb3nnXWMLz6zFZ49EUADTMO5RJsLEMAJMuukmBq41A==
2024-04-12T15:49:21.432587000Z Disconnection happened, type: Websocket.Client.DisconnectionInfo
2024-04-12T15:49:21.433031000Z Connection lost reconnect to Websocket...
2024-04-12T15:49:21.436012000Z Disconnection happened, type: Websocket.Client.DisconnectionInfo
2024-04-12T15:49:21.437447000Z Done!
2024-04-12T15:49:21.445113000Z Disconnection happened, type: Websocket.Client.DisconnectionInfo
2024-04-13T06:53:26.310039000Z warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
2024-04-13T06:53:26.310352000Z       Failed to determine the https port for redirect.
2024-04-13T07:01:10.849199000Z info: Microsoft.Hosting.Lifetime[0]
2024-04-13T07:01:10.849976000Z       Application is shutting down...
2024-04-13T07:01:19.743943000Z Database is created: True
2024-04-13T07:01:20.253000000Z Gotify - Url: https://gotify.blackert.eu
2024-04-13T07:01:20.253371000Z Is Gotify - Url available: yes
2024-04-13T07:01:20.253531000Z SecNtfy Server - Url: https://api.secntfy.app
2024-04-13T07:01:20.253652000Z Is SecNtfy Server - Url available: yes
2024-04-13T07:01:20.254088000Z Client - Token: CvGefF6TVajoIbK
2024-04-13T07:01:20.258488000Z Client connecting...
2024-04-13T07:01:20.292499000Z Done!
2024-04-13T07:01:20.308369000Z info: Microsoft.Hosting.Lifetime[14]
2024-04-13T07:01:20.308500000Z       Now listening on: http://[::]:8080
2024-04-13T07:01:20.310539000Z info: Microsoft.Hosting.Lifetime[0]
2024-04-13T07:01:20.310624000Z       Application started. Press Ctrl+C to shut down.
2024-04-13T07:01:20.311279000Z info: Microsoft.Hosting.Lifetime[0]
2024-04-13T07:01:20.311343000Z       Hosting environment: Production
2024-04-13T07:01:20.311377000Z info: Microsoft.Hosting.Lifetime[0]
2024-04-13T07:01:20.311415000Z       Content root path: /app
2024-04-13T07:01:32.337135000Z warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
2024-04-13T07:01:32.337385000Z       Failed to determine the https port for redirect.
`

**Comment by androidseb25** [comment]
erste Zeile des logs

`2024-04-12T14:56:44.631569000Z Unhandled exception. System.Net.Http.HttpRequestException: Name or service not known (gotify.blackert.eu:443) `

der kommt an deinen Gotify nicht ran!

Entweder verhindert, wenn vorhanden deine FW das oder was anderes im Netzwerk löst die Verbindung nicht auf

**Comment by andre1808** [comment]
Hm. Dann sollte er aber generell Probleme haben oder? Nach einem Neustart des Containers läuft es eigentlich immer wieder. 
Firewall seitig blocke ich auch nichts. Glaube der Fehler ist eher weil zu dem Zeitpunkt gotify noch nicht lief - kann das sein?

ps: kannst du meine Domain rauseditieren? Hab auf dem Handy das Logo nicht komplett durchgelesen und gefiltert 😅

**Comment by androidseb25** [comment]
ja es kann gut möglich sein das der gotify server später da ist als mein service...

aber teilweise die reconnect versuche hatten ja auch nicht geklappt, so wie ich im log sehe

Deine Domain und andere Daten hab ich rausgelöscht

**Comment by andre1808** [comment]
Ich gucke gleich nochmal nach dem einkaufen ob ich vielleicht was im nginx sehen kann oder so. 
Danke dir schonmal!

**Comment by andre1808** [comment]
Hallo Seb.
Ich hab nochmal geguckt (sorry, hat etwas länger gedauert - hab das Wetter ausgenutzt und war Tennis spielen :))
Also was ich sehen kann, war gotify.domain.com durchgängig online, mit der Ausnahme, wenn ich Backups mache, oder anderweitig händisch was war (z.B. hab ich gestern versehentlich den Strom gezogen :D)

Ich mache in der Nacht von Sonntag zu Montag um 1 Uhr ein Backup meine Proxmox LXCs und VMs. Aber ansonsten ist alles durchgängig up. Bin etwas ratlos :(

**Comment by androidseb25** [comment]
mmmmh da fällt mir auch nichts mehr ein, es muss definitiv was bei dir sein, da bei meinen Teststellungen und in meiner Produktiv, sowie Arbeitsumgebung läuft das alles tadellos :/ 

ich lass den Issue mal offen vielleicht gibt es noch weitere mit dem selben Problem

**Comment by andre1808** [comment]
Heute Nacht liefen die Backups und zumindest aktuell scheint noch alles zu laufen.
Ich beobachte es mal weiter :)

**Comment by dia5ha** [comment]
Sorry, habe das gleiche Problem. Verliere täglich die Verbindung und nach Neustart des Containers funktioniert es wieder. So wie ich es aus meinen Logs entnehmen zu meine, passiert es immer nach Zwangstrennung durch Provider. Aber vielleicht mache ich auch etwas falsch.

**Comment by dia5ha** [comment]
Schaut dann so aus: 2024-04-15T16:28:05.473851745Z Disconnection happened, type: Websocket.Client.DisconnectionInfo
2024-04-15T16:28:05.473882755Z Disconnection happened, type: Websocket.Client.DisconnectionInfo
2024-04-15T16:28:05.473888970Z Connection lost reconnect to Websocket...
2024-04-15T16:28:05.473894208Z Connection lost reconnect to Websocket...
2024-04-15T16:28:05.475272374Z Disconnection happened, type: Websocket.Client.DisconnectionInfo
2024-04-15T16:28:05.475298704Z Disconnection happened, type: Websocket.Client.DisconnectionInfo
2024-04-15T16:28:05.476670513Z Done!
2024-04-15T16:28:05.476700056Z Done!
2024-04-15T16:28:05.477993016Z Disconnection happened, type: Websocket.Client.DisconnectionInfo
2024-04-15T16:28:05.478433780Z Disconnection happened, type: Websocket.Client.DisconnectionInfo

**Comment by androidseb25** [comment]
Ok das selbe was oben ist, komisch ist das es eine `DisconnectionInfo` ist normalerweise wenn es einen Disconnect gibt steht dort `DisconnectionLost`

Das sieht nach einer Lokalen Netzwerk Problem aus sonst würde er die dauerhaft halten.

Ich kann um das Problem zu fixen einen optionalen flag hinzufügen der ein reconnect durchführt bei der DisconnectionInfo, was aber dahinführen kann das er in ein Loop gerät und mehrere Connection eröffnet und man mehrfach Nachrichten bekommt...

Bitte schaut nochmal ob es nicht doch bei euch nen Problem im Netzwerk gibt.

Ansonsten sagt nochmal Bescheid dann würde ich die Option einbauen

**Comment by andre1808** [comment]
Also ich wüsste wirklich nicht was bei mir lokalen Netzwerk dazwischen funken könnte ehrlich gesagt :(
Ich hab alles unter proxmox laufen. IGotify und Gotify laufen in einem lxc Container mit Docker installiert und watchtower für Updates. Sonst läuft darauf nichts. 

Ein weiter lxc Container beherbergt Nginx Proxy Manager als Reverse Proxy. Ich habe derzeit keine unterschiedliche VLANs und alles läuft in einer IP Range.
Andere Container haben bisweilen keine Probleme gezeigt.
Auch Gotify selbst ist erreichbar, auch wenn die Pushnachrichten nicht mehr zugestellt werden. Öffne ich deine App erscheinen auch die Nachrichten - es ist also echt nur das Push was ein Problem macht :(

von daher fände ich eine reconnect Option cool. 
wenn nicht muss ich halt hin und wieder den Container durchstarten 😅

**Comment by androidseb25** [comment]
Bitte versucht mal die neue Version, hab den Workflow des WebSockets nochmal überarbeitet, vielleicht hilft das schon.

https://github.com/androidseb25/iGotify-Notification-Assistent/releases/tag/v1.2.0.3

Falls der Fehler wieder auftritt bitte Issue nochmal öffnen

**Comment by andre1808** [comment]
Vielen Dank. 
Ich werde es mal probieren und berichten :)
Danke für deinen tollen Support!

**Comment by dia5ha** [comment]
Bin begeistert, mit neuer Version rennt es jetzt bei mir mit Push Notifications auf phone und watch. Log sieht nach Restart Container auch super aus:
2024-04-16T14:46:33.603857225Z Client connecting...
2024-04-16T14:46:33.638466734Z Done!
2024-04-16T14:49:40.255990058Z Disconnection happened, type: Lost
2024-04-16T14:49:40.256030076Z Connection lost reconnect to Websocket...
2024-04-16T14:49:40.257242649Z Disconnection happened, type: ByUser
2024-04-16T14:49:40.271322513Z Disconnection happened, type: Error
2024-04-16T14:49:40.271347306Z Webseocket Reconnection failed with Error. Try to reconnect in 10s.
2024-04-16T14:49:50.283344868Z Gotify with Clienttoken: "xxxxxxxxxxx" is successfully reconnected!
Vielen Dank für das tolle Projekt und den tollen Support!

**Comment by androidseb25** [comment]
super das freut mich das es jetzt klappt :D 

Kein Problem der Support gehört dazu ^^

**Comment by andre1808** [comment]
Wollte nochmal kurz Feedback hinterlassen:
Nachdem ich gerade meine HDD im Raid austauschen musste und vergessen hatte meinen DNS wieder hochzufahren, hatte iGotify natürlich Probleme mit der Verbindung.
Der Reconnect funktionierte aber perfekt! Sobald mein DNS wieder erreichbar war, war iGotify wieder bereit :)

`2024-04-16T19:17:07.972875000Z Gotify Server is not available try to reconnect in 10s.
2024-04-16T19:17:17.975008000Z Reconnecting...
2024-04-16T19:17:33.990184000Z Gotify Server is not available try to reconnect in 10s.
2024-04-16T19:17:43.991028000Z Reconnecting...
2024-04-16T19:18:00.006881000Z Gotify Server is not available try to reconnect in 10s.
2024-04-16T19:18:10.008415000Z Reconnecting...
2024-04-16T19:18:26.024232000Z Gotify Server is not available try to reconnect in 10s.
2024-04-16T19:18:36.021551000Z Reconnecting...
2024-04-16T19:18:36.755729000Z Gotify - Url: https://gotify.domain.com
2024-04-16T19:18:36.756220000Z Is Gotify - Url available: yes
2024-04-16T19:18:36.756472000Z SecNtfy Server - Url: https://api.secntfy.app
2024-04-16T19:18:36.756633000Z Is SecNtfy Server - Url available: yes
2024-04-16T19:18:36.756737000Z Client - Token: xxx
2024-04-16T19:18:36.761676000Z Client connecting...
2024-04-16T19:18:36.809536000Z Done!`

Also nochmals großes Lob ;)

**Comment by androidseb25** [comment]
perfekt das freut mich das es funktioniert ^^
