### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DonPablo1010** [androidseb25/iGotify-Notification-Assistent#82]
**Describe the bug**
Es erscheint seit heute Morgen eine SSL Fehlermeldung in der iOS App. Der Token kann nicht übertragen werden.

**Expected behavior**
Die App sollte die Instanz(en) via Token normal erreichen können. Verbindung über https:// Url über Nginx Reverse Proxy Manager. Bis heute Nacht hatte alles normal funktioniert.

**Screenshots**
![IMG_9181](https://github.com/user-attachments/assets/d065b869-8317-45ff-b2d8-487bac60ca55)

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro / iPhone 15
 - OS: iOS17.5.1
 - Version of Container: 2.5.0
 - Version of iGotify: 1.3.2

**Additional context**
Allenfalls ist der Bug Apple bezogen (Key / Verschlüsselung), da auch die App WebSSH seit heute Morgen die gespeicherten SSH Keys nicht mehr handeln kann?

**Comment by DonPablo1010** [comment]
Relevanter Auszug Portainer Log des igotify Containers:

The SSL connection could not be established, see inner exception.
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at SecNtfyNuGet.SecNtfy.GetPubKeyFromDevice(String deviceToken)

Das Zertifikat ist jedoch gültig und wenn ich die Url über einen Browser aufrufe gibt es keine Zertifikatsfehler.

**Comment by androidseb25** [comment]
Ist ein Problem bei mir SSL Zertifikat ist ungültig warum auch immer, hatte das vor kurzem aktualisiert, erneuere es dann später bin gerade unterwegs 😅

**Comment by Huntback52** [comment]
i've got the same error as @DonPablo1010

**Comment by Huntback52** [comment]
error log:
The SSL connection could not be established, see inner exception.
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at SecNtfyNuGet.SecNtfy.GetPubKeyFromDevice(String deviceToken)

**Comment by androidseb25** [comment]
the problem must be fixed now there is a new cert in the background service

**Comment by Huntback52** [comment]
@androidseb25 , thanks for the quick fix 👍

**Comment by DonPablo1010** [comment]
> the problem must be fixed now there is a new cert in the background service

Thx for the real quick answer an fix; as allways!🙌🏼

**Comment by DonPablo1010** [comment]
Was fixed but noe appers again!!😱

![IMG_9184](https://github.com/user-attachments/assets/0a95cfa3-c587-413c-b741-81dbb2e52399)
