### ISSUE TITLE
[BUG]Error Socketservice.

### ISSUE THREAD

**Issue by ne0ark** [androidseb25/iGotify-Notification-Assistent#96]
**Describe the bug**
Language of description allowed: English/German

**Expected behavior**

**Screenshots**
```   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService.StartConnection(System.Collections.Generic.List`1<iGotify_Notification_Assist.Models.Users>, System.String)
   at iGotify_Notification_Assist.Services.GotifySocketService+<StartDelayedConnection>d__13.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[iGotify_Notification_Assist.Services.GotifySocketService+<StartDelayedConnection>d__13, iGotify Notification Assist, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[iGotify_Notification_Assist.Services.GotifySocketService+<StartDelayedConnection>d__13, iGotify Notification Assist, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[iGotify_Notification_Assist.Services.GotifySocketService+<StartDelayedConnection>d__13, iGotify Notification Assist, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Threading.Tasks.Task.TrySetResult()
   at System.Threading.Tasks.Task+DelayPromise.CompleteTimedOut()
   at System.Threading.TimerQueueTimer.Fire(Boolean)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()```

**Smartphone (please complete the following information):**
 - Version of Container [e.g. 1.0.0.7]
 - Version of iGotify [e.g. 1.0.5]

**Additional context**
I see following error in the log. Not sure what's causing it.

**Comment by androidseb25** [comment]
it seems that you're gotify isn't online!

he goes in a loop to try reconnecting 

See in the code here:
https://github.com/androidseb25/iGotify-Notification-Assistent/blob/db065518f5a5b1742f4ed0ac16382944e7eeec7b/Services/GotifySocketService.cs#L166

**Comment by androidseb25** [comment]
s this error still actually?

When no this Issue will be closed on day 30.
